### ISSUE TITLE
Allow Job/schedule to be deleted

### ISSUE THREAD

**Issue by pmbanugo** [pmbanugo/cron-atlas#4]
Implementing an easy means to delete jobs from the UI

**Comment by abakermi** [comment]
@pmbanugo ,I think #4 already implemented?

**Comment by pmbanugo** [comment]
> @pmbanugo ,I think #4 already implemented?

Yes, that’s been done. I’ll close this issue. 

@abakermi Do you want to contribute to any of the open issue? Or are there areas you’re more interested in?

**Comment by abakermi** [comment]
@pmbanugo I like to contribute on any issue still open or not mentioned

**Comment by pmbanugo** [comment]
@abakermi what about #1 ?

**Comment by pmbanugo** [comment]
Or implement a basic user profile page
